name: KPU_ALGO

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: mkdir build folder
      run: mkdir build && cd build
    - name: cmake
      run: cmake ..
    - name: make
      run: make
    - name: make check
      run: make check
