name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
